name: quiz_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
flutter_sdk_version: 3.27.1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8.

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  get: 4.6.6
  get_storage: 2.1.1


flutter:
  uses-material-design: true

  assets:
    - assets/json/quiz.json

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
